### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by sendos** [sendos/matlab_utils_for_python#1]
![utils_test](https://cloud.githubusercontent.com/assets/1019930/25138827/7cbedd04-2453-11e7-8fbf-df5295887587.png)

**Comment by sendos** [comment]
![utils_test2](https://cloud.githubusercontent.com/assets/1019930/25139464/369c8432-2455-11e7-8378-4af55cb18553.png)

**Comment by sendoswww** [comment]
![utils_test3](https://cloud.githubusercontent.com/assets/1019930/25139608/ae41864a-2455-11e7-8c56-9f05ec15fefc.png)

**Comment by sendos** [comment]
![utils_test4](https://cloud.githubusercontent.com/assets/1019930/25139782/3c0b6ce8-2456-11e7-88a2-e9be395e306c.png)
